stages:
#  - test
  - staging
  - prod

###
# Run tests.
###
#test:
#  stage: test
#  script:
#    - tox -e py36
#  tags:
#    - linux


preprod5000:
  stage: staging
  script:
    - echo $iqsshkey > iq.creds
    - chmod 0400 iq.creds
    - scp -R-i iq.creds * ubuntu@ingredients.quebec:/tmp
#  when: on_success
  tags:
    - linux

prod:
  stage: prod
  script:
    - ssh in the box and git pull
    - restart gunicorn
  when: manual
  tags:
    - linux
